# In-Class Programming Activity, Day 6

Your work goes here ...


##Task 1
```{r}
myHistogram = function(fill){
  nbins = 10
  d = min(Galton$height):max(Galton$height)
  evenly_spaced = seq(min(Galton$height),max(Galton$height),(max(Galton$height)-min(Galton$height))/(nbins))
  bin_counts=table(cut(Galton$height, breaks = evenly_spaced))
  xL = evenly_spaced[1:length(bin_counts)]
  xR = evenly_spaced[2:(length(bin_counts)+1)]
  count = as.numeric(bin_counts)
  hist_basics= data.frame(xL,xR, count)
  
  make_one_bar <- function(point) {
  xLeft <- point$xL
  xRight <- point$xR
  height <- point$count
  res <- data.frame(
              x = c(xLeft,  xLeft,  xRight, xRight, NA),
              y = c(    0, height,  height,      0, NA)
  )
  res
  }
  # ================
  one_to_five <- function(hist_data) {
    bars <- NULL
    for (k in 1:nrow(hist_data)) {
      new_bar <- make_one_bar(hist_data[k, ])
      bars <- rbind(bars, new_bar)
    }
    bars
  }
  
  My_bars = one_to_five(hist_basics)
  

  d_mean = mean(Galton$height)
  d_sd = sd(Galton$height)
  plot(My_bars, type="n") 
  lines(dnorm(Galton$height,d_mean,d_sd), add=T, col='red')
  lines(My_bars)
  polygon(My_bars, col = fill)
  lines(dnorm(Galton$height,d_mean,d_sd), add=T, col='red')
  return(bin_counts)
}
```

##Task 2
```{r}
v <- rnorm(10, mean=100, sd=1)

```

##Task 3
##Task 4
##Task 5
## Test statements

```{r}
scoreActivity::score253(6)
```