# In-Class Programming Activity, Day 8
# Pradyut Bansal  
Your work goes here ...

# Task 1
```{r}
x =runif(100,20,70)
My_data = data.frame(
  x = x,
  y = 5+3*x+2*rnorm(100)
  )
plot(My_data)

LL_line = function(params){
  m = params[1]
  b = params[2]
  sigma = params[3]
  return(sum(log(dnorm(My_data[,2]- (m * My_data[,1] + b), sd = sigma))))
}

testA = LL_line(c(3,5,2))
testB = LL_line(c(4,1,10))

starting_params <- c(4, 1, 10)
best <- optim(starting_params, LL_line, control=list(fnscale = -1))

```


#task 2

```{r}
load(url("http://tiny.cc/dcf/Taxi_trips.rda"))
waiting_fare <- Taxi_trips$fare_amount - (Taxi_trips$base_fare + Taxi_trips$per_mile*Taxi_trips$trip_distance)

taxi_likelihood= function(vector1){
  base_fare = vector1[1]
  per_mile = vector1[2]
  params = vector1[3]
  
  return(sum(log(dexp(Taxi_trips$fare_amount- (base_fare * waiting_fare + per_mile),params)+1^-100)))
}

starting_params=c(base_fare = 2.00, per_mile = 4.00, params = 1/3)
best <- optim(starting_params, taxi_likelihood, control=list(fnscale = -1))
best
plot(Taxi_trips$fare_amount,Taxi_trips$trip_distance)
```


## Test statements

```{r}
scoreActivity::score253(8)
```